UPDATE products SET color = 'Dark Brown', season = 'Fall/Winter', material = 'Leather', gender = 'Men', style = 'Casual', size = 'XS,S,M,L,XL,XXL' WHERE name = 'Dark Brown Leather Bomber Jacket';
UPDATE products SET color = 'Olive', season = 'All Season', material = 'Cotton', gender = 'Men', style = 'Casual', size = 'XS,S,M,L,XL,XXL' WHERE name = 'Olive Cotton Five-Pocket Trousers';
UPDATE products SET color = 'Sand', season = 'Spring/Summer', material = 'Linen', gender = 'Men', style = 'Tailored', size = 'XS,S,M,L,XL,XXL' WHERE name = 'Sand Belted Linen Trench Coat';
UPDATE products SET color = 'Light Blue', season = 'Spring/Summer', material = 'Denim', gender = 'Men', style = 'Casual', size = 'XS,S,M,L,XL,XXL' WHERE name = 'Light Blue Denim Bermuda Shorts';
UPDATE products SET color = 'Navy', season = 'Fall/Winter', material = 'Technical Fabric', gender = 'Men', style = 'Sporty', size = 'XS,S,M,L,XL,XXL' WHERE name = 'Navy Storm System® Coat';
UPDATE products SET color = 'Blush Pink', season = 'Spring/Summer', material = 'Cotton', gender = 'Men', style = 'Casual', size = 'XS,S,M,L,XL,XXL' WHERE name = 'Blush Pink Cotton T-Shirt';
UPDATE products SET color = 'Navy', season = 'All Season', material = 'Denim', gender = 'Men', style = 'Casual', size = 'XS,S,M,L,XL,XXL' WHERE name = 'Navy Denim Field Jacket';
UPDATE products SET color = 'Dark Khaki', season = 'Fall/Winter', material = 'Wool', gender = 'Men', style = 'Tailored', size = 'XS,S,M,L,XL,XXL' WHERE name = 'Dark Khaki Pleated Wool Trousers';
UPDATE products SET color = 'Storm Blue', season = 'Fall/Winter', material = 'Technical Fabric', gender = 'Men', style = 'Sporty', size = 'XS,S,M,L,XL,XXL' WHERE name = 'Storm Blue Windmate Gilet';
UPDATE products SET color = 'Navy', season = 'Spring/Summer', material = 'Denim', gender = 'Men', style = 'Casual', size = '39,40,41,42,43,44,45' WHERE name = 'Navy Denim Boat Shoes';
UPDATE products SET color = 'Beige', season = 'Spring/Summer', material = 'Linen', gender = 'Men', style = 'Tailored', size = 'XS,S,M,L,XL,XXL' WHERE name = 'Beige Double-Breasted Linen Blazer';
UPDATE products SET color = 'Brown', season = 'All Season', material = 'Suede', gender = 'Men', style = 'Casual', size = '39,40,41,42,43,44,45' WHERE name = 'Brown Suede Sneakers';
UPDATE products SET color = 'Camel', season = 'Fall/Winter', material = 'Wool', gender = 'Women', style = 'Tailored', size = 'XS,S,M,L,XL,XXL' WHERE name = 'Camel Single-Breasted Wool Coat';
UPDATE products SET color = 'Black', season = 'Fall/Winter', material = 'Shearling', gender = 'Women', style = 'Casual', size = 'XS,S,M,L,XL,XXL' WHERE name = 'Black Shearling Hooded Coat';
UPDATE products SET color = 'Ivory', season = 'All Season', material = 'Canvas', gender = 'Women', style = 'Casual', size = NULL WHERE name = 'Ivory Canvas Zip Wallet';
UPDATE products SET color = 'Burgundy', season = 'Fall/Winter', material = 'Suede', gender = 'Women', style = 'Casual', size = 'XS,S,M,L,XL,XXL' WHERE name = 'Burgundy Suede Overshirt';
UPDATE products SET color = 'Lavender', season = 'Fall/Winter', material = 'Bouclé', gender = 'Women', style = 'Elegant', size = 'XS,S,M,L,XL,XXL' WHERE name = 'Lavender Bouclé Belted Dress';
UPDATE products SET color = 'White', season = 'Fall/Winter', material = 'Technical Fabric', gender = 'Women', style = 'Sporty', size = 'XS,S,M,L,XL,XXL' WHERE name = 'White Hooded Ski Jacket';
UPDATE products SET color = 'Blush Pink', season = 'All Season', material = 'Suede', gender = 'Women', style = 'Casual', size = '39,40,41,42,43,44,45' WHERE name = 'Blush Pink Suede Sneakers';
UPDATE products SET color = 'Rust', season = 'Fall/Winter', material = 'Wool', gender = 'Women', style = 'Tailored', size = 'XS,S,M,L,XL,XXL' WHERE name = 'Rust Double-Breasted Wool Coat';
UPDATE products SET color = 'Red', season = 'Fall/Winter', material = 'Acetate', gender = 'Women', style = 'Sporty', size = NULL WHERE name = 'Red Ski Goggles';
UPDATE products SET color = 'Ivory', season = 'Fall/Winter', material = 'Wool Knit', gender = 'Women', style = 'Casual', size = 'XS,S,M,L,XL,XXL' WHERE name = 'Ivory Cable-Knit Midi Skirt';
UPDATE products SET color = 'White', season = 'Fall/Winter', material = 'Technical Fabric', gender = 'Women', style = 'Sporty', size = 'XS,S,M,L,XL,XXL' WHERE name = 'White Storm System® Ski Pants';
UPDATE products SET color = 'Cognac', season = 'All Season', material = 'Leather', gender = 'Women', style = 'Elegant', size = NULL WHERE name = 'Cognac Mini Leather Bag';
UPDATE products SET color = 'Dark Grey', season = 'All Season', material = 'Leather', gender = 'Women', style = 'Elegant', size = NULL WHERE name = 'Dark Grey Leather Clutch';
UPDATE products SET color = 'Navy', season = 'Fall/Winter', material = 'Cashmere', gender = 'Unisex', style = 'Casual', size = NULL WHERE name = 'Navy Ribbed Cashmere Beanie';
UPDATE products SET color = 'Ivory', season = 'All Season', material = 'Leather', gender = 'Unisex', style = 'Elegant', size = NULL WHERE name = 'Ivory Leather Baby Stroller';
UPDATE products SET color = 'Black', season = 'All Season', material = 'Suede', gender = 'Women', style = 'Casual', size = '39,40,41,42,43,44,45' WHERE name = 'Black Suede Mule Slippers';
UPDATE products SET color = 'Taupe', season = 'All Season', material = 'Leather', gender = 'Men', style = 'Casual', size = NULL WHERE name = 'Taupe Leather Belt';
UPDATE products SET color = 'Charcoal', season = 'Fall/Winter', material = 'Cashmere', gender = 'Unisex', style = 'Elegant', size = NULL WHERE name = 'Charcoal Cashmere Throw';
UPDATE products SET color = 'Rose Gold', season = 'Spring/Summer', material = 'Acetate', gender = 'Women', style = 'Elegant', size = NULL WHERE name = 'Rose Gold Acetate Sunglasses';
UPDATE products SET color = 'Ivory', season = 'Fall/Winter', material = 'Wool', gender = 'Men', style = 'Casual', size = 'XS,S,M,L,XL,XXL' WHERE name = 'Ivory Wool Field Jacket';
UPDATE products SET color = 'Dark Brown', season = 'All Season', material = 'Cashmere', gender = 'Men', style = 'Formal', size = NULL WHERE name = 'Dark Brown Cashmere Tie';
UPDATE products SET color = 'Black', season = 'All Season', material = 'Technical Fabric', gender = 'Unisex', style = 'Sporty', size = NULL WHERE name = 'Black Technical Backpack';
UPDATE products SET color = 'Dark Brown', season = 'All Season', material = 'Suede', gender = 'Unisex', style = 'Elegant', size = NULL WHERE name = 'Dark Brown Suede Fedora Hat';
UPDATE products SET color = 'Black', season = 'All Season', material = 'Suede', gender = 'Men', style = 'Formal', size = '39,40,41,42,43,44,45' WHERE name = 'Black Suede Loafers';
UPDATE products SET color = 'Neutral', season = 'Fall/Winter', material = 'Cashmere', gender = 'Unisex', style = 'Casual', size = 'XS,S,M,L,XL,XXL' WHERE name = 'Essential Cable Knit Sweater';
UPDATE products SET color = 'Neutral', season = 'Fall/Winter', material = 'Merino Wool', gender = 'Unisex', style = 'Casual', size = 'XS,S,M,L,XL,XXL' WHERE name = 'Essential Merino Turtleneck';
UPDATE products SET color = 'Neutral', season = 'Fall/Winter', material = 'Cashmere', gender = 'Unisex', style = 'Casual', size = 'XS,S,M,L,XL,XXL' WHERE name = 'Essential Cashmere Trousers';
UPDATE products SET color = 'Neutral', season = 'Fall/Winter', material = 'Cashmere', gender = 'Unisex', style = 'Casual', size = NULL WHERE name = 'Essential Cashmere Scarf';
UPDATE products SET color = 'Neutral', season = 'All Season', material = 'Cashmere', gender = 'Unisex', style = 'Casual', size = 'XS,S,M,L,XL,XXL' WHERE name = 'Essential Cashmere Polo';
UPDATE products SET color = 'Neutral', season = 'Fall/Winter', material = 'Merino Wool', gender = 'Unisex', style = 'Casual', size = 'XS,S,M,L,XL,XXL' WHERE name = 'Essential Wool Turtleneck';
UPDATE products SET color = 'Neutral', season = 'All Season', material = 'Cashmere Blend', gender = 'Women', style = 'Elegant', size = 'XS,S,M,L,XL,XXL' WHERE name = 'Essential Palazzo Pants';
UPDATE products SET color = 'Neutral', season = 'Fall/Winter', material = 'Cashmere', gender = 'Unisex', style = 'Casual', size = NULL WHERE name = 'Essential Knit Beanie';
UPDATE products SET color = 'Neutral', season = 'All Season', material = 'Cashmere', gender = 'Unisex', style = 'Casual', size = NULL WHERE name = 'Essential Soft Scarf';
UPDATE products SET color = 'Neutral', season = 'All Season', material = 'Leather', gender = 'Unisex', style = 'Casual', size = NULL WHERE name = 'Essential Leather Wallet';
UPDATE products SET color = 'Neutral', season = 'Fall/Winter', material = 'Cashmere', gender = 'Unisex', style = 'Casual', size = NULL WHERE name = 'Essential Cashmere Gloves';
UPDATE products SET color = 'Neutral', season = 'Fall/Winter', material = 'Cashmere', gender = 'Unisex', style = 'Casual', size = NULL WHERE name = 'Essential Winter Beanie';
UPDATE products SET color = 'Brown', season = 'Fall/Winter', material = 'Wool', gender = 'Men', style = 'Casual', size = 'S,M,L,XL' WHERE name = 'Cable Knit Wool Cardigan';
UPDATE products SET color = 'White', season = 'All Season', material = 'Cotton', gender = 'Men', style = 'Formal', size = 'S,M,L,XL,XXL' WHERE name = 'Classic Cotton Shirt';
UPDATE products SET color = 'Beige', season = 'Fall/Winter', material = 'Wool', gender = 'Men', style = 'Tailored', size = 'S,M,L,XL' WHERE name = 'Pleated Wool Trousers';
UPDATE products SET color = 'Navy', season = 'Fall/Winter', material = 'Wool', gender = 'Men', style = 'Casual', size = 'S,M,L' WHERE name = 'Wool Flat Cap';
UPDATE products SET color = 'Brown', season = 'Fall/Winter', material = 'Wool Tweed', gender = 'Women', style = 'Tailored', size = 'XS,S,M,L,XL' WHERE name = 'Tweed Stand-Collar Jacket';
UPDATE products SET color = 'Camel', season = 'Fall/Winter', material = 'Wool Felt', gender = 'Women', style = 'Formal', size = 'S,M,L' WHERE name = 'Wide-Brim Wool Hat';
UPDATE products SET color = 'Leopard', season = 'All Season', material = 'Silk', gender = 'Women', style = 'Formal', size = '38,39,40,41,42' WHERE name = 'Leopard Print Bow Loafers';
UPDATE products SET color = 'Brown', season = 'Fall/Winter', material = 'Wool', gender = 'Women', style = 'Tailored', size = 'XS,S,M,L,XL' WHERE name = 'Wide-Leg Checked Wool Trousers';
